version: '3.3'

# Current AWS Inbound Rules:
# 7501 - 7505: Web Challenges
# 7601 - 7605: Crypto Challenges
# 7701 - 7705: RE Challenges
# 7801 - 7805: Pwnable Challenges

services:
  # Web challenges (ports 7501-7505)
  web_post_malone:
    build: ./src/challenges/web/post_malone
    restart: always
    ports:
     - "7501:7501"
   
  web_the_client_is_always_right:
    build: ./src/challenges/web/the_client_is_always_right
    restart: always
    ports:
     - "7502:7502"

  web_no_peeking:
    build: ./src/challenges/web/no_peeking
    restart: always
    ports:
     - "7503:7503"
  
  web_the_hunt:
    build: ./src/challenges/web/the_hunt
    restart: always
    ports:
     - "7504:7504"
  
  # Crypto challenges (ports 7601-7605)
  crypto_caesar_salad:
    build: ./src/challenges/crypto/caesar_salad
    restart: always
    ports:
      - "7601:7601"
    stdin_open: true
    tty: true

  crypto_the_oracle_of_time:
    build: ./src/challenges/crypto/the_oracle_of_time
    restart: always
    ports:
      - "7602:7602"
    stdin_open: true
    tty: true

  # RE challenges (ports 7701-7705)
  re_bussin:
    build: ./src/challenges/re/bussin
    restart: always
    ports:
      - "7701:7701"
    stdin_open: true
    tty: true
  
  # Pwnable challenges (ports 7801-7805)
  pwn_information_disclosure:
    build: ./src/challenges/pwn/information_disclosure
    restart: always
    ports:
      - "7801:7801"
    stdin_open: true
    tty: true

  pwn_ret2win:
    build: ./src/challenges/pwn/ret2win
    restart: always
    ports:
      - "7802:7802"
    stdin_open: true
    tty: true
