version: '3.3'

services:
  # Web challenges (ports 7501-7505)
  web_post_malone:
    build: ./src/challenges/web/post_malone
    restart: always
    ports:
     - "7501:7501"
   
  web_the_client_is_always_right:
    build: ./src/challenges/web/the_client_is_always_right
    restart: always
    ports:
     - "7502:7502"

  # Crypto challenges (ports 7601-7605)
  crypto_caesar_salad:
    build: ./src/challenges/crypto/caesar_salad
    restart: always
    ports:
      - "7601:7601"
    stdin_open: true
    tty: true

  crypto_the_oracle_of_time:
    build: ./src/challenges/crypto/the_oracle_of_time
    restart: always
    ports:
      - "7602:7602"
    stdin_open: true
    tty: true