origin: https://ctf.hthackers.com
faviconUrl: https://images.squarespace-cdn.com/content/v1/5e1d245285d6d83067bd591f/dc953fa3-0e19-4a43-9eda-74529906f0cd/favicon.ico?format=100w
divisions:
  open: Open
tokenKey: '70uEBo6LGyXY7pvU2/ctspdUJ53klrhX1rWVNdQkEXc='
startTime: 1667480400000
endTime: 1667584800000
